### ISSUE TITLE
Can you upload the requirements file?

### ISSUE THREAD

**Issue by qwasdw** [sunghoonhong/AirsimDRL#4]
I can't run your code

**Comment by sunghoonhong** [comment]
Hi,

As I mentioned in README, I'm sorry that I totally didn't consider reproduction.
So, I don't have requirements file as well.

I think you will suffer some troubles related to tensorflow, keras, or airsim version.
I remember that I used the newest versions at the time, 2 years ago. (tensorflow 1, keras, airsim)
I'm sorry again and thanks for your attention.

Best
