### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sumzora** [sunghoonhong/AirsimDRL#5]
I have some questions about your code.
what's the meanig of goals list  (goals = [7, 17, 27.5, 45, goalY] ) and what's the level of a list in computing the reward ( goals[self.level] )?  
 I just know the fifth figure(57) is the  goal position in y axis. 
would you like to tell the other figures' meaning. 
Thank you so much

**Comment by sunghoonhong** [comment]
Hi,

First, thanks for your attention.

1. meaning of goals
It is a kind of reward engineering.
`goals` consists of several subgoals, which encourages the agent to overcome obstacles till the agent reaches the final goal.
As you figured out, the elements in `goals` represent each goal position in the y-axis.

2. meaning of level
It represents how many subgoals the agent has reached.

Best
